dbt_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      ######## Please replace with your Snowflake account name
      account: IPPONPARTNER.EU_WEST_1

      user: '196530'
      ######## Please replace with your Snowflake dbt user password
      password: Testing4!

      role: MTENAUD_ROLE
      database: MTENAUD_DB
      warehouse: MTENAUD_WH_XS
      schema: PUBLIC
      threads: 200